### ISSUE TITLE
PHP Fatal error:  Call to undefined function jsond_encode() in Command line code on line 1

### ISSUE THREAD

**Issue by Alexdener** [bukka/php-jsond#14] opened 2016-04-07 14:42 UTC
![image](https://cloud.githubusercontent.com/assets/11288868/14354926/bc0e74ac-fd11-11e5-93b0-fb24038eecf3.png)

Jsond extension has been installed,but jsond_encode() cannot be used.
Can you give some help ?

**Comment by bukka** [comment] 2016-04-10 15:15
I guess that you use master. Then please see #12 . It automatically replaces json functions by default... I will need to update doc once I release 1.4 (it means once I port it to PHP 7...) but it's a duplicate of #12 so closing.

**Closed by bukka** 2016-04-10 15:15 UTC
